/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/sample_user_tags": {
    get: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.sample_user_tags.user_id"];
          tag_id?: parameters["rowFilter.sample_user_tags.tag_id"];
          created_at?: parameters["rowFilter.sample_user_tags.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sample_user_tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sample_user_tags */
          sample_user_tags?: definitions["sample_user_tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.sample_user_tags.user_id"];
          tag_id?: parameters["rowFilter.sample_user_tags.tag_id"];
          created_at?: parameters["rowFilter.sample_user_tags.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.sample_user_tags.user_id"];
          tag_id?: parameters["rowFilter.sample_user_tags.tag_id"];
          created_at?: parameters["rowFilter.sample_user_tags.created_at"];
        };
        body: {
          /** sample_user_tags */
          sample_user_tags?: definitions["sample_user_tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/sample_tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_tags.id"];
          name?: parameters["rowFilter.sample_tags.name"];
          rate?: parameters["rowFilter.sample_tags.rate"];
          created_at?: parameters["rowFilter.sample_tags.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sample_tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sample_tags */
          sample_tags?: definitions["sample_tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_tags.id"];
          name?: parameters["rowFilter.sample_tags.name"];
          rate?: parameters["rowFilter.sample_tags.rate"];
          created_at?: parameters["rowFilter.sample_tags.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_tags.id"];
          name?: parameters["rowFilter.sample_tags.name"];
          rate?: parameters["rowFilter.sample_tags.rate"];
          created_at?: parameters["rowFilter.sample_tags.created_at"];
        };
        body: {
          /** sample_tags */
          sample_tags?: definitions["sample_tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tags": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          created_at?: parameters["rowFilter.tags.created_at"];
          user_id?: parameters["rowFilter.tags.user_id"];
          name?: parameters["rowFilter.tags.name"];
          weight?: parameters["rowFilter.tags.weight"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tags"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          created_at?: parameters["rowFilter.tags.created_at"];
          user_id?: parameters["rowFilter.tags.user_id"];
          name?: parameters["rowFilter.tags.name"];
          weight?: parameters["rowFilter.tags.weight"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tags.id"];
          created_at?: parameters["rowFilter.tags.created_at"];
          user_id?: parameters["rowFilter.tags.user_id"];
          name?: parameters["rowFilter.tags.name"];
          weight?: parameters["rowFilter.tags.weight"];
        };
        body: {
          /** tags */
          tags?: definitions["tags"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/sample_users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_users.id"];
          first_name?: parameters["rowFilter.sample_users.first_name"];
          last_name?: parameters["rowFilter.sample_users.last_name"];
          gender?: parameters["rowFilter.sample_users.gender"];
          created_at?: parameters["rowFilter.sample_users.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sample_users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sample_users */
          sample_users?: definitions["sample_users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_users.id"];
          first_name?: parameters["rowFilter.sample_users.first_name"];
          last_name?: parameters["rowFilter.sample_users.last_name"];
          gender?: parameters["rowFilter.sample_users.gender"];
          created_at?: parameters["rowFilter.sample_users.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sample_users.id"];
          first_name?: parameters["rowFilter.sample_users.first_name"];
          last_name?: parameters["rowFilter.sample_users.last_name"];
          gender?: parameters["rowFilter.sample_users.gender"];
          created_at?: parameters["rowFilter.sample_users.created_at"];
        };
        body: {
          /** sample_users */
          sample_users?: definitions["sample_users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Join table for many-to-many relation between users and interests tables */
  sample_user_tags: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `sample_users.id`.<fk table='sample_users' column='id'/>
     */
    user_id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `sample_tags.id`.<fk table='sample_tags' column='id'/>
     */
    tag_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
  };
  /** @description Interest tags */
  sample_tags: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    name: string;
    /** Format: real */
    rate: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
  };
  tags: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: uuid */
    user_id?: string;
    /** Format: character varying */
    name?: string;
    /** Format: real */
    weight?: number;
  };
  sample_users: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: character varying */
    first_name: string;
    /** Format: character varying */
    last_name: string;
    /** Format: character varying */
    gender: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description sample_user_tags */
  "body.sample_user_tags": definitions["sample_user_tags"];
  /** Format: bigint */
  "rowFilter.sample_user_tags.user_id": string;
  /** Format: bigint */
  "rowFilter.sample_user_tags.tag_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.sample_user_tags.created_at": string;
  /** @description sample_tags */
  "body.sample_tags": definitions["sample_tags"];
  /** Format: bigint */
  "rowFilter.sample_tags.id": string;
  /** Format: character varying */
  "rowFilter.sample_tags.name": string;
  /** Format: real */
  "rowFilter.sample_tags.rate": string;
  /** Format: timestamp with time zone */
  "rowFilter.sample_tags.created_at": string;
  /** @description tags */
  "body.tags": definitions["tags"];
  /** Format: bigint */
  "rowFilter.tags.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.tags.created_at": string;
  /** Format: uuid */
  "rowFilter.tags.user_id": string;
  /** Format: character varying */
  "rowFilter.tags.name": string;
  /** Format: real */
  "rowFilter.tags.weight": string;
  /** @description sample_users */
  "body.sample_users": definitions["sample_users"];
  /** Format: bigint */
  "rowFilter.sample_users.id": string;
  /** Format: character varying */
  "rowFilter.sample_users.first_name": string;
  /** Format: character varying */
  "rowFilter.sample_users.last_name": string;
  /** Format: character varying */
  "rowFilter.sample_users.gender": string;
  /** Format: timestamp with time zone */
  "rowFilter.sample_users.created_at": string;
}

export interface operations {}

export interface external {}
